apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-config
  namespace: revenue-forecast
data:
  DB_USER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "retail_db"
  CSV_PATH: "/data/online_retail_data.csv"
  ARIMA_PATH: "models/arima_model.pkl"
  SARIMA_PATH: "models/sarima_model.pkl"
  METRICS_PATH: "models/metrics.json"

---
apiVersion: v1
kind: Secret
metadata:
  name: retail-secret
  namespace: revenue-forecast
type: Opaque
stringData:
  DB_PASS: "111204"
